#!/usr/bin/env bash
# install-litert-ios-framework.sh
#
# Copies the vendored LiteRT-LM iOS XCFramework from this repo into the
# react-native-litert-lm node_modules folder where CocoaPods expects it.
#
# Why this script exists: the upstream package has a postinstall that
# tries to download a prebuilt XCFramework from
# `github.com/hung-yueh/react-native-litert-lm/releases/download/vX.Y.Z/`,
# but no version 0.1.0 through 0.3.4 has ever published that asset
# (HTTP 404 confirmed Apr 2026). Without the framework, iOS builds link
# nothing and the LiteRT-LM Nitro module fails to resolve at runtime.
#
# So we keep our own prebuilt XCFramework in `vendor/litert-ios/`,
# committed to git, and copy it into node_modules on every `npm install`
# (chained from package.json's postinstall hook).
#
# This script is a no-op on non-macOS hosts because the upstream package
# only ships iOS native code on darwin anyway.

set -euo pipefail

if [ "$(uname)" != "Darwin" ]; then
  echo "[litert-ios] non-macOS host, skipping iOS framework install."
  exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
VENDORED="$PROJECT_ROOT/vendor/litert-ios/LiteRTLM.xcframework"
DEST_DIR="$PROJECT_ROOT/node_modules/react-native-litert-lm/ios/Frameworks"

if [ ! -d "$VENDORED" ]; then
  echo "[litert-ios] No vendored XCFramework at $VENDORED — skipping (run scripts/build-ios-engine.sh in node_modules to build one and commit it)."
  exit 0
fi

if [ ! -d "$PROJECT_ROOT/node_modules/react-native-litert-lm" ]; then
  echo "[litert-ios] react-native-litert-lm not in node_modules — skipping."
  exit 0
fi

mkdir -p "$DEST_DIR"

# Skip the XCFramework copy if the destination already has the same
# binary (large directory copy — only worth doing when there's a real
# change). Compare the device-slice binary by content, not Info.plist
# — Info.plist is regenerated by the build script with stable
# contents, so plist equality doesn't imply binary equality. This
# bit us once after a rebuild: vendor had the new framework, plist
# matched, copy was skipped, node_modules kept stale binary.
SRC_BIN="$VENDORED/ios-arm64/LiteRTLM.framework/LiteRTLM"
DEST_BIN="$DEST_DIR/LiteRTLM.xcframework/ios-arm64/LiteRTLM.framework/LiteRTLM"
if [ -d "$DEST_DIR/LiteRTLM.xcframework" ] && \
   [ -f "$SRC_BIN" ] && [ -f "$DEST_BIN" ] && \
   cmp -s "$SRC_BIN" "$DEST_BIN"; then
  echo "[litert-ios] XCFramework already in place, skipping copy."
else
  echo "[litert-ios] Copying LiteRTLM.xcframework into node_modules..."
  rm -rf "$DEST_DIR/LiteRTLM.xcframework"
  cp -R "$VENDORED" "$DEST_DIR/LiteRTLM.xcframework"
fi

# Sync cpp/include/litert_lm_engine.h with the vendored XCFramework's
# authoritative header. The npm package ships a stale 509-line copy
# under cpp/include/ from upstream v0.3.4 that uses the old short-name
# API (InputData, kInputText, kTopP). Our vendored XCFramework is a
# newer build with the verbose-name API (LiteRtLmInputData,
# kLiteRtLmInputDataTypeText, kLiteRtLmSamplerTypeTopP), and the
# patched HybridLiteRTLM.cpp targets the new names — so without this
# sync the build picks up the stale include and 5 symbols fail to
# resolve at compile time. Both XCFramework slices ship identical
# headers, so we copy from ios-arm64.
SRC_HEADER="$VENDORED/ios-arm64/LiteRTLM.framework/Headers/litert_lm_engine.h"
DEST_HEADER="$PROJECT_ROOT/node_modules/react-native-litert-lm/cpp/include/litert_lm_engine.h"
if [ -f "$SRC_HEADER" ] && [ -d "$(dirname "$DEST_HEADER")" ]; then
  cp "$SRC_HEADER" "$DEST_HEADER"
  echo "[litert-ios] Synced cpp/include/litert_lm_engine.h with vendored framework."
fi

# Vendored Hybrid wrapper patches:
#   - tryCreateEngine accepts a third audioBackend arg and we call it with
#     nullptr, nullptr for vision and audio. Skips multimodal executor
#     init that crashes on iOS because the Bazel-built XCFramework lacks
#     vision and audio ops.
#   - createNewConversation / sendMessageInternal / sendMessageAsync use
#     the Session API (litert_lm_engine_create_session +
#     session_generate_content). The Conversation API constructs a
#     re2::RE2 from the model's chat-template string, which crashes for
#     vision-aware Gemma 4 on our XCFramework (heap corruption when
#     vision_executor is null). Session API skips the prompt-template
#     compile entirely; we wrap the prompt in <start_of_turn>…<end_of_turn>
#     manually so Gemma 4 still gets a proper instruction turn.
#   - Header gains LiteRtLmSession* session_ field and StreamContext
#     gains promptBuffer to keep the formatted prompt alive across the
#     async streaming callback.
#   - Three calls to litert_lm_get_last_error() commented out (symbol not
#     in our XCFramework export list).
# We vendor the whole files instead of carrying a patch, because
# patch-package failed to parse the diff for this version of the package.
PATCHED_CPP="$PROJECT_ROOT/vendor/litert-cpp/HybridLiteRTLM.cpp"
DEST_CPP="$PROJECT_ROOT/node_modules/react-native-litert-lm/cpp/HybridLiteRTLM.cpp"
if [ -f "$PATCHED_CPP" ] && [ -d "$(dirname "$DEST_CPP")" ]; then
  cp "$PATCHED_CPP" "$DEST_CPP"
  echo "[litert-ios] Replaced HybridLiteRTLM.cpp with vendored patched copy."
fi

PATCHED_HPP="$PROJECT_ROOT/vendor/litert-cpp/HybridLiteRTLM.hpp"
DEST_HPP="$PROJECT_ROOT/node_modules/react-native-litert-lm/cpp/HybridLiteRTLM.hpp"
if [ -f "$PATCHED_HPP" ] && [ -d "$(dirname "$DEST_HPP")" ]; then
  cp "$PATCHED_HPP" "$DEST_HPP"
  echo "[litert-ios] Replaced HybridLiteRTLM.hpp with vendored patched copy."
fi

# EngineInit per-slice archives. Each contains just engine_impl.o
# extracted from the corresponding framework slice, force-loaded by
# the patched podspec so the LITERT_LM_REGISTER_ENGINE static
# initialiser survives Apple's linker dead-code stripping. These
# MUST stay in sync with the vendored framework — extracting from
# v0.10.1's framework but linking v1.x's framework yields ABI errors
# (engine_impl.o references absl::lts_X while the framework defines
# absl::lts_Y). The rebuild-litert-xcframework.sh script always
# re-extracts both pieces in lockstep.
ENGINE_INIT_SRC="$PROJECT_ROOT/vendor/litert-ios/EngineInit"
ENGINE_INIT_DEST="$PROJECT_ROOT/node_modules/react-native-litert-lm/ios/EngineInit"
if [ -d "$ENGINE_INIT_SRC" ]; then
  rm -rf "$ENGINE_INIT_DEST"
  cp -R "$ENGINE_INIT_SRC" "$ENGINE_INIT_DEST"
  echo "[litert-ios] Installed EngineInit per-slice archives."
fi

# Vendored podspec — patches s.user_target_xcconfig with the
# -force_load on the per-slice EngineInit/libengine_init.a so the
# engine registration symbol survives the final app link.
PATCHED_PODSPEC="$PROJECT_ROOT/vendor/litert-podspec/react-native-litert-lm.podspec"
DEST_PODSPEC="$PROJECT_ROOT/node_modules/react-native-litert-lm/react-native-litert-lm.podspec"
if [ -f "$PATCHED_PODSPEC" ] && [ -f "$DEST_PODSPEC" ]; then
  cp "$PATCHED_PODSPEC" "$DEST_PODSPEC"
  echo "[litert-ios] Replaced podspec with vendored patched copy (-force_load applied)."
fi

echo "[litert-ios] ✅ XCFramework + wrapper + EngineInit + podspec installed. Run \`npx pod-install ios\` next."
